version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    # ports:
    #   - "9100:9100"
    expose:
      - "9100"
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    # expose:
    #   - "9090"
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/web.yml:/etc/prometheus/web.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
      - --storage.tsdb.retention.time=31d
    env_file:
      - ./envs/prod/prometheus/.env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3010:3010"
    networks:
      - monitoring
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ./envs/prod/grafana/.env

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
